disabled_rules: # rule identifiers to exclude from running
  - missing_docs
  - unused_closure_parameter
  - trailing_whitespace
  - identifier_name

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules: # some rules are only opt-in
  - empty_count
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  # - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  # - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywordss
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

dentifier_name:
  excluded:
    - id
number_separator:
  minimum_length: 5

included: # paths to include during linting. `--path` is ignored if present.
  - Bobot
  - BobotTest

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - ../Pods
  - ./Pods
  - /Pods
  - Bobot/R.generated.swift
  - Bobot/Pods
  - ApolloCodegen

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300

function_body_length:
  - 300 # warning
  - 400 # error

function_parameter_count:
  - 10 # warning
  - 15 # error

large_tuple:
  - 6 # warning
  - 12 # error

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 1000
  error: 2000

cyclomatic_complexity:
  - 30 # warning
  - 100 # error

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - T
    - E

identifier_name:
  allowed_symbols:
    - _
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - vc
    - id
    - in
    - kf
    - x
    - y
